Update patch set 1
Patch Set 1:

Ole is correct. It won't build with imports removed from vppapigen.py. I tested only Centos build so far,
APIGEN   vlibmemory/memclnt.api.h
  JSON API vlibmemory/memclnt.api.json
NameError: global name 'lex' is not defined
...

Patch-set: 1
Reviewer: Gerrit User 32 <32@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>
Label: Code-Review=0