ipsec: fix gcc build breakage due to __clib_packed warning
- this test escape happened due to incorrect vpp build action
  return status on failure
- fixes this warning (note: vnet_crypto_alg_t is __clib_packed
  in the typedef):

FAILED: CMakeFiles/vnet/CMakeFiles/vnet_objs.dir/ipsec/ipsec_sa.c.o
/usr/bin/ccache /usr/lib/ccache/gcc -DCLIB_DEBUG -DHAVE_FCNTL64 -I/scratch/docker-build/vpp/src -I/scratch/docker-build/vpp/build-root/build-vpp_debug-native/vpp/CMakeFiles -I/scratch/docker-build/vpp/build-root/build-vpp_debug-native/vpp/CMakeFiles/vnet -fPIC -Wno-stringop-overflow -Wno-stringop-overread -Wno-array-bounds -g -Werror -Wall -Wno-address-of-packed-member -O0 -fstack-protector -fno-common -march=x86-64-v2 -mtune=generic -MD -MT CMakeFiles/vnet/CMakeFiles/vnet_objs.dir/ipsec/ipsec_sa.c.o -MF CMakeFiles/vnet/CMakeFiles/vnet_objs.dir/ipsec/ipsec_sa.c.o.d -o CMakeFiles/vnet/CMakeFiles/vnet_objs.dir/ipsec/ipsec_sa.c.o -c /scratch/docker-build/vpp/src/vnet/ipsec/ipsec_sa.c
/scratch/docker-build/vpp/src/vnet/ipsec/ipsec_sa.c:28:3: error: ‘packed’ attribute ignored for field of type ‘vnet_crypto_alg_t’ [-Werror=attributes]
   28 |   vnet_crypto_alg_t alg __clib_packed;
      |   ^~~~~~~~~~~~~~~~~
/scratch/docker-build/vpp/src/vnet/ipsec/ipsec_sa.c:29:3: error: ‘packed’ attribute ignored for field of type ‘vnet_crypto_alg_t’ [-Werror=attributes]
   29 |   vnet_crypto_alg_t esn_alg __clib_packed;
      |   ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Type: fix

Change-Id: Iad01d1faf60157439dbaea0821df0559795956c3
Signed-off-by: Dave Wallace <dwallacelf@gmail.com>