vlib: add LSB standard exit codes if vpp doesn't start properly
VPP currently returns 0 if it cannot start.

  * return non-zero exit codes so the parent process can
    have a hint as to the error.

  * adds the exit codes as an enum to the api

  In the test framework, this changes:
    framework.VppDiedError: VPP subprocess died unexpectedly
    with return code: 0 [].
  to:
    framework.VppDiedError: VPP subprocess died unexpectedly
    with return code: 153 [VLIB_THREAD_INIT].

https://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/iniscrptact.html

Type: feature
Change-Id: Iafc441f9b5a5f1b0499eb13b12579870b783e7f8
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>