Update patch set 1
Patch Set 1: Code-Review-2

vapi_c_gen doesn't handle:
              "string",
                "name",
                {
                    "limit": 64
                }

/vpp/memclnt/src/vpp-api/vapi/vapi_c_gen.py --remove-path /vpp/memclnt/build-root/build-vpp_debug-native/vpp/vlibmemory/memclnt.api.json
Traceback (most recent call last):
  File "/vpp/memclnt/src/vpp-api/vapi/vapi_c_gen.py", line 795, in <module>
    gen_c_unified_headers(jsonparser, logger, args.prefix, args.remove_path)
  File "/vpp/memclnt/src/vpp-api/vapi/vapi_c_gen.py", line 751, in gen_c_unified_headers
    parser, logger, j, io, json_to_c_header_name(f))
  File "/vpp/memclnt/src/vpp-api/vapi/vapi_c_gen.py", line 715, in gen_json_unified_header
    emit_definition(parser, j, emitted, t)
  File "/vpp/memclnt/src/vpp-api/vapi/vapi_c_gen.py", line 634, in emit_definition
    print("%s" % o.get_c_def())
  File "/vpp/memclnt/src/vpp-api/vapi/vapi_c_gen.py", line 119, in get_c_def
    for x in self.fields])),
  File "/vpp/memclnt/src/vpp-api/vapi/vapi_c_gen.py", line 17, in get_c_def
    return "%s %s[%d];" % (self.type.get_c_name(), self.name, self.len)
TypeError: %d format: a number is required, not dict

Patch-set: 1
Label: Code-Review=-2