Update patch set 4
Patch Set 4:

Hi Damjan,
Could you please review this code change? It is also to resolve the build error on 64Byte cache line Arm CPUs, e.g., ThunderX2, NeoverseN1, caused by the commit (https://gerrit.fd.io/r/c/vpp/+/32996, build: remove unused files and sections).

src/plugins/dpdk/device/init.c:1916:3: error: static_assert failed due to requirement '128 == 1 << 6' "DPDK RTE CACHE LINE SIZE does not match with 1<<CLIB_LOG2_CACHE_LINE_BYTES"
  STATIC_ASSERT (RTE_CACHE_LINE_SIZE == 1 << CLIB_LOG2_CACHE_LINE_BYTES,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lijian/tasks/plsremove/src/vppinfra/error_bootstrap.h:111:34: note: expanded from macro 'STATIC_ASSERT'
#define STATIC_ASSERT(truth,...) _Static_assert(truth, __VA_ARGS__)
                                 ^              ~~~~~
1 error generated.

Patch-set: 4
Reviewer: Gerrit User 1431 <1431@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>
Label: Code-Review=0