Tests: fix TypeErrors in test/test_jvpp.py
Fixes:
TypeError: __init__() takes at least 3 arguments (2 given).

Due to a pycodestyle bug.

Change-Id: I0f52086447d0ff87814e3ec79a4232c7a44e1b31
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>