Update patch set 2
Patch Set 2:

> Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from os import path, remove
> >>> path.exists('/tmp/filt.pcap')
> False
> >>> remove('/tmp/filt.pcap')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/filt.pcap'
> >>>

Agreed.  In your test, you are using remove, not os.remove.
They both need to be os.<foo> or <foo>.  
The FileNotFoundError is due to the earlier portion of the code being skipped in the REPL.

As to whether it should be path or os.path, see: https://stackoverflow.com/questions/710551/use-import-module-or-from-module-import

Reading through the replies in post you can see that 
a) less code is not imported by using from `os import path` and 
b) from `os import path` is more likely to cause circular references (especially when trying to write tests, which is more important in the framework and vpp_<foo> code), but do we want to make primarily non-python developers remember all the corner cases?

Patch-set: 2