Update patch set 3
Patch Set 3:

(3 comments)

I think build is failing due to:
Generating JVpp callback facade
/w/workspace/vpp-csit-verify-virl/build-data/../vpp-api/java/jvpp/org/openvpp/jvpp/test/CallbackJVppFacadeTest.java:35: error: illegal start of expression
    private static ShowVersionCallback showVersionCallback1 = msg ->
                                                                   ^
/w/workspace/vpp-csit-verify-virl/build-data/../vpp-api/java/jvpp/org/openvpp/jvpp/test/CallbackJVppFacadeTest.java:40: error: illegal start of expression
    private static ShowVersionCallback showVersionCallback2 = msg ->
                                                                   ^
2 errors
Error: Could not find class file for 'org.openvpp.jvpp.VppJNIConnection'.
Error: Could not find class file for 'org.openvpp.jvpp.JVppImpl'.

??

Patch-set: 3
Label: Code-Review=0