Update patch set 2
Patch Set 2: Code-Review-1

Downstream RHEL doesn't have 'subunit'.

Build Error:
Getting requirements for vpp-17.10-rc1~20_g8a4fdd9.src
 --> systemd-219-42.el7.x86_64
 --> chrpath-0.16-0.el7.x86_64
 --> check-0.9.9-5.el7.x86_64
 --> check-devel-0.9.9-5.el7.x86_64
Error: No Package found for subunit

Patch-set: 2
Label: Code-Review=-1