tests: make UnexpectedApiReturnValueError friendlier
NOTE: THIS IS CURRENTLY RUNNING EXTENDED_TESTS=1 test-debug IN THE CI.
  ** DO NOT COMMIT IN THIS STATE OR ALL JOBS WILL FAIL !!! **

- Make the api exception more user and test friendly.
- Introduce new api fn. api_strerror_dump(api_errno=0x7fffffff) for
  list of api errorcode definitions.

Change output from:
  UnexpectedApiReturnValueError: API call failed, expected 0 return value instead of -6 in
  bridge_domain_add_del_reply(_0=148, context=14988, retval=-6)

to:
  UnexpectedApiReturnValueError: sw_interface_add_del_address(address_length=24, is_add=1,
  sw_if_index=3, address='\xac\x10\x01\x02')
  returned 'Address already present on another interface.' (-127).  Expected 0.
  Reply was: sw_interface_add_del_address_reply(_0=89, context=38, retval=-127).

Enable tests to access api values/replies.
    with self.assertRaises(UnexpectedApiReturnValueError) as unexpected:
	rv=self.vapi.foo()
	if expected.rv == -60:
	  bar()

    Provides the following to the tests:
        self.ev
        self.rv
        self.reply
        self.api_fn_name
        self.api_fn_args

Type: feature

Change-Id: Ifdabc9db1d0d72c6cd06f666ebc10763c2768747
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>