vapi: fix vapi_c_gen.py support for defaults
Fix:
Traceback (most recent call last):
  File "/vpp/src/vpp-api/vapi/vapi_c_gen.py", line 795, in <module>
    gen_c_unified_headers(jsonparser, logger, args.prefix, args.remove_path)
  File "/vpp/src/vpp-api/vapi/vapi_c_gen.py", line 751, in gen_c_unified_headers
    parser, logger, j, io, json_to_c_header_name(f))
  File "/vpp/src/vpp-api/vapi/vapi_c_gen.py", line 715, in gen_json_unified_header
    emit_definition(parser, j, emitted, t)
  File "/vpp/src/vpp-api/vapi/vapi_c_gen.py", line 634, in emit_definition
    print("%s" % o.get_c_def())
  File "/vpp/src/vpp-api/vapi/vapi_c_gen.py", line 119, in get_c_def
    for x in self.fields])),
  File "/vpp/src/vpp-api/vapi/vapi_c_gen.py", line 17, in get_c_def
    return "%s %s[%d];" % (self.type.get_c_name(), self.name, self.len)
TypeError: %d format: a number is required, not dict

Type: fix

Change-Id: Icce777b6c2de8dd5295b685fc2600db48e529d90
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>