Update patch set 2
Patch Set 2: Code-Review-1

Constant change of quickly version starts to be annoying, as it requires rebuilding ext deps package. Can you implement version check so quic plugin is disabled if satisfying version is not found instead of breaking build like this one:

/home/dmarion/cisco/vpp/src/plugins/quic/quic_crypto.c:258:5: error: implicit declaration of function ‘quicly_get_next_expected_packet_number’; did you mean ‘quicly_determine_packet_number’? [-Werror=implicit-function-declaration]
  258 |     quicly_get_next_expected_packet_number (qctx->conn);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     quicly_determine_packet_number

Patch-set: 2
Reviewer: Gerrit User 9 <9@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>
Label: Code-Review=-1