make:  Update .gitignore
https://gerrit.fd.io/r/#/c/20286/ introduces build files that
should be ignored.

$ git review -f
Errors running git rebase -p -i remotes/gerrit/master
error: The following untracked working tree files would be overwritten by checkout:
	test/requirements-2.txt
Please move or remove them before you can switch branches.
Aborting

Type: fix
Fixes: 28fa8cbc6c635758db1a885fd5ae2ff8719569c3

Change-Id: I435427ebebf9f3c0cacf986f7cfd28bde5cac756
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>