Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> How would you get into a situation where you have sparse message ids or duplicate message ids?
> (Does this patch ensure then that you don't connect? Or does it fail silently?)

From my understanding, sockclnt_create_reply returns all the messages from msg_index_by_name_and_crc, so not registered in runtime (for example due registration disabled) are not returned and therefore are not going into py message_table. After that id_names and id_msgdef has insufficient length, but indexed by runtime message ids in _register_function():
    self.id_msgdef[i] = msg
IndexError: list assignment index out of range

Since shmem_api uses max message id since the very start, issues was not really noticeable, keeping all the plugins built produces same effect for socket api.
So, keeping same behavior for calculating max id looks to me as feature parity here w/o need to change the rest parts of vpp api side and/or papi.

Patch-set: 1