Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > See examples in vpp_stats.py. stats[counter].sum() should give you what you need. Personally I would prefer not to have another wrapper in framework.py, but use vpp_stats directly.
> 
> What do you mean? Replacing the summing line produces:
> 
>   File "/home/ksekera/vpp/test/framework.py", line 1219, in assert_counter_equal
>     c = self.get_counter(counter, thread, index)
>   File "/home/ksekera/vpp/test/framework.py", line 1206, in get_counter
>     counter_value = counter_value[index].sum
> AttributeError: 'list' object has no attribute 'sum'

Counters can be accessed in either dimension.
stat['/if/rx'] - returns 2D lists
stat['/if/rx'][0] - returns counters for all interfaces for thread 0
stat['/if/rx'][0][1] - returns counter for interface 1 on thread 0
stat['/if/rx'][0][1]['packets'] - returns the packet counter
                                  for interface 1 on thread 0
stat['/if/rx'][:, 1] - returns the counters for interface 1 on all threads
stat['/if/rx'][:, 1].packets() - returns the packet counters for
                                 interface 1 on all threads
stat['/if/rx'][:, 1].sum_packets() - returns the sum of packet counters for
                                     interface 1 on all threads
stat['/if/rx-miss'][:, 1].sum() - returns the sum of packet counters for
                                  interface 1 on all threads for simple counters

I would prefer to remove the get_counter() in framework.py.
I don't see any users of it. And screen scraping "show errors" also is not required.

Patch-set: 1