Update patch set 2
Patch Set 2:

> Downstream RHEL doesn't have 'subunit'.
 > 
 > Build Error:
 > Getting requirements for vpp-17.10-rc1~20_g8a4fdd9.src
 > --> systemd-219-42.el7.x86_64
 > --> chrpath-0.16-0.el7.x86_64
 > --> check-0.9.9-5.el7.x86_64
 > --> check-devel-0.9.9-5.el7.x86_64
 > Error: No Package found for subunit

That's very interesting, because check requires subunit. Centos doesn't have the dependency, so installing check only results in a non-working check (due to runtime issue because subunit is not there). It only starts working once subunit is added (from the repo) by hand.

I always thought that centos is a rhel ripoff .. how come rhel doesn't have subunit?

Patch-set: 2
Label: Verified=0