test framework.py Handle missing docstring gracefully.
If a TestCase is missing a docstring, the TestRunner crashes
due to an attributeError.
==============================================================================
ERROR: setUpClass (test_pg.PGTest)
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/vpp/test/framework.py", line 413, in setUpClass
    cls.print_header()
  File "/vpp/test/framework.py", line 279, in print_header
    print(colorize(getdoc(cls).splitlines()[0], GREEN))
AttributeError: 'NoneType' object has no attribute 'splitlines'
==============================================================================

This patch handles the missing docstring.
==============================================================================
PGTestNoStreamsConfigured (Please add docstring to TestCase).
==============================================================================

Change-Id: If25906ee4dd4c15979392099cf4721d63bdc7d7c
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>