gbp: fix the failure during "make test-debug"
The GBP unittest reliability improvement patch causes a failure
in "make test-debug", with the below diagnostic. This changes back
the setting on what appears to be a trigger, while keeping
the rest of the adjustments intact.

GBP Test Case
==============================================================================
Group Based Policy                                                   30.09 OK
14:23:08,351 REG: Couldn't remove configuration for object(s):
14:23:08,351 <gbp-endpoint:[0==21:10.0.0.201:113]>
GBP Anonymous L3 Out                                                 8.62 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]
GBP BD arp flags                                                     0.36 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]
GBP BD drop flags                                                    0.38 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]
GBP Contracts                                                        0.42 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]
GBP L3 Out                                                           0.42 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]
GBP L2 Endpoint Learning                                             0.42 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]
GBP L3 Endpoint Learning                                             0.43 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]
GBP L2 Endpoint w/ VLANs                                             0.39 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]
GBP Endpoint Redirect                                                0.43 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]
GBP Endpoint Redirect Extended                                       0.43 ERROR [ temp dir used by test case: /tmp/vpp-unittest-TestGBP-r048jhdj ]

==============================================================================
ERROR: GBP Anonymous L3 Out

Change-Id: Ia6e4962b65fef30965427e915ac67cea334befc1

------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/vpp/build-root/build-test/src/test_gbp.py", line 610, in tearDown
    super(TestGBP, self).tearDown()
  File "/home/ubuntu/vpp/test/framework.py", line 698, in tearDown
    self.registry.remove_vpp_config(self.logger)
  File "/home/ubuntu/vpp/test/vpp_object.py", line 107, in remove_vpp_config
    raise Exception("Couldn't remove configuration for object(s): %s" %
Exception: Couldn't remove configuration for object(s): gbp-endpoint:[0==21:10.0.0.201:113]

==============================================================================

Fixes: 8d0d8d2fcccd77e462f30b21f7f8810db312ee62
Type: fix
Signed-off-by: Andrew Yourtchenko <ayourtch@gmail.com>
Change-Id: I57da17c7a2a9c06ca9185db96b6bd2af77eb0a30