API: Fix missing attribute in memclnt_delete.
logging(DEBUG) under vpp_papi identified:
  'memclnt_delete' object has no attribute 'context'

(What should the api version be bumped to in this case?)

{0} test.api.test_memclnt_api.TestMemclntApiSingleThread.test_memclnt_delete [0.000575s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/vpp/test/api/test_memclnt_api.py", line 36, in test_memclnt_delete
        do_cleanup=1)
      File "/vpp/.tox/py27/local/lib/python2.7/site-packages/vpp_papi/vpp_papi.py", line 101, in __call__
        return self._func(**kwargs)
      File "/vpp/.tox/py27/local/lib/python2.7/site-packages/vpp_papi/vpp_papi.py", line 416, in f
        return self._call_vpp(i, msg, multipart, **kwargs)
      File "/vpp/.tox/py27/local/lib/python2.7/site-packages/vpp_papi/vpp_papi.py", line 620, in _call_vpp
        self.validate_args(msgdef, kwargs)
      File "/vpp/.tox/py27/local/lib/python2.7/site-packages/vpp_papi/vpp_papi.py", line 588, in validate_args
        .format(list(d), msg.name))
    vpp_papi.vpp_papi.VPPValueError: Invalid argument ['context'] to memclnt_delete

Change-Id: I6b986588048250b6039097073036094f9f5b8679
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>