nat: fix nat44-ed outside address distribution
Use thread-distribution-like hash to pick the first address
instead of just src address high octet, becasue it may denegerate
into stable 10/172/192, depending on nat address count.

Loop over all VRF independent addresses if there's no configured
VRF dependent ones. This allows to keep picking addresses (if any)
in case of hashed port falures and speedups the picking as well.
Add brief per-VRF address count stats as well.

Fix outside address distribution test to acually test the
distribution, not the algo, so previous distribution will fail with
65 nat addresses and 100 clients:

FAIL: Outside address distribution based on source address
Change-Id: Ib4bfc34718ce21f0b770306a7c4767baabac8ade
------------------------------------------------------------------------------
Traceback (most recent call last):
  File ".../test/test_nat44_ed.py", line 2048, in test_outside_address_distribution
    msg="Too uneven outside address distribution")
AssertionError: 156.25 not less than 0.33 : Too uneven outside address distribution

Type: improvement
Change-Id: I6ebada6e744084587b41cc11f1c3baa72c7b31ce
Signed-off-by: Vladislav Grishenko <themiron@yandex-team.ru>