tests: ensure host has enough cores for test
TestIPv4MWReassembly and TestIPv6MWReassembly are configured for
4 workers and a main thread, without checking for
sufficient cores on the host.

The console shows:
    ==============================================================================
    ERROR: setUpClass (test_reassembly.TestIPv4MWReassembly)
    ------------------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/vagrant/vpp/test/test_reassembly.py", line 680, in setUpClass
        super(TestIPv4MWReassembly, cls).setUpClass()
      File "/home/vagrant/vpp/test/framework.py", line 564, in setUpClass
        cls.statistics = VPPStats(socketname=cls.stats_sock)
      File "/home/vagrant/vpp/src/vpp-api/python/vpp_papi/vpp_stats.py", line 216, in __init__
        raise VPPStatsIOError(retval=rv)
    vpp_papi.vpp_stats.VPPStatsIOError: Stat segment client connection returned: -2 Stat client socket open but couldn't connect.

but further digging in the logs shows the root cause:
    /vpp/build-root/install-vpp-native/vpp/bin/vpp[8851]: vlib_thread_init: no available cpus to be used for the 'workers' thread

Type: fix
Fixes: 630ab5846bceddf8d663e9f488a2dc0378949827

Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>
Change-Id: I3a6346d2b8ed0519bd27e587301822cd965339a6