vppinfra: silence GCC 11 -Wmaybe-uinitialized warning
Building VPP with GCC 11 will output the following errors. Fix this
issue by initializing the pointer to null in the beginning.

[973/2771] /usr/bin/ccache /usr/lib/ccache/gcc-11 -DCLIB_MARCH_VARIANT=cortexa72 -DHAVE_FCNTL64 -D_FORTIFY_SOURCE=2 -I/home/jiewan01/tasks/vpp_rdma/64B/src -ICMakeFiles -ICMakeFiles/vnet -fPIC   -Wno-stringop-overflow -g -Werror -Wall -Wno-address-of-packed-member -O3 -fstack-protector -fno-common -march=armv8-a+crc+crypto -mtune=cortex-a72 -DCLIB_N_PREFETCHES=6 -DCLIB_LOG2_CACHE_PREFETCH_BYTES=6 -MD -MT CMakeFiles/vnet/CMakeFiles/vnet_cortexa72.dir/ipsec/esp_encrypt.c.o -MF CMakeFiles/vnet/CMakeFiles/vnet_cortexa72.dir/ipsec/esp_encrypt.c.o.d -o CMakeFiles/vnet/CMakeFiles/vnet_cortexa72.dir/ipsec/esp_encrypt.c.o   -c /home/jiewan01/tasks/vpp_rdma/64B/src/vnet/ipsec/esp_encrypt.c
FAILED: CMakeFiles/vnet/CMakeFiles/vnet_cortexa72.dir/ipsec/esp_encrypt.c.o
/usr/bin/ccache /usr/lib/ccache/gcc-11 -DCLIB_MARCH_VARIANT=cortexa72 -DHAVE_FCNTL64 -D_FORTIFY_SOURCE=2 -I/home/jiewan01/tasks/vpp_rdma/64B/src -ICMakeFiles -ICMakeFiles/vnet -fPIC   -Wno-stringop-overflow -g -Werror -Wall -Wno-address-of-packed-member -O3 -fstack-protector -fno-common -march=armv8-a+crc+crypto -mtune=cortex-a72 -DCLIB_N_PREFETCHES=6 -DCLIB_LOG2_CACHE_PREFETCH_BYTES=6 -MD -MT CMakeFiles/vnet/CMakeFiles/vnet_cortexa72.dir/ipsec/esp_encrypt.c.o -MF CMakeFiles/vnet/CMakeFiles/vnet_cortexa72.dir/ipsec/esp_encrypt.c.o.d -o CMakeFiles/vnet/CMakeFiles/vnet_cortexa72.dir/ipsec/esp_encrypt.c.o   -c /home/jiewan01/tasks/vpp_rdma/64B/src/vnet/ipsec/esp_encrypt.c
In file included from /home/jiewan01/tasks/vpp_rdma/64B/src/vlib/node_funcs.h:51,
                 from /home/jiewan01/tasks/vpp_rdma/64B/src/vlib/error_funcs.h:43,
                 from /home/jiewan01/tasks/vpp_rdma/64B/src/vlib/vlib.h:74,
                 from /home/jiewan01/tasks/vpp_rdma/64B/src/vnet/buffer.h:43,
                 from /home/jiewan01/tasks/vpp_rdma/64B/src/vnet/vnet.h:49,
                 from /home/jiewan01/tasks/vpp_rdma/64B/src/vnet/ipsec/esp_encrypt.c:18:
/home/jiewan01/tasks/vpp_rdma/64B/src/vnet/ipsec/esp_encrypt.c: In function ‘esp4_encrypt_node_fn_cortexa72’:
/home/jiewan01/tasks/vpp_rdma/64B/src/vppinfra/interrupt.h:81:7: error: ‘interrupts’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

Type: fix
Fixes: cc8249c5fde1 ("vlib: interrupt mode support for pre-input nodes")
Signed-off-by: Jieqiang Wang <jieqiang.wang@arm.com>
Change-Id: I4bcd2525dfd8e3fface9f3a60f4e43b3f5d7cd46