Update patch set 2
Patch Set 2:

Can we revert this code its causing build failure in Qualcomm.
FYI: Apart from ThunderX or I am not sure OcteonTx all the other ARM machines have 64B cache line size. Can you please categorize the else statement only for Cavium Machines.

FAILED: plugins/dpdk/CMakeFiles/dpdk_plugin.dir/device/init.c.o 
ccache /usr/lib/ccache/cc -DHAVE_MEMFD_CREATE -Ddpdk_plugin_EXPORTS -I/home/sirdas/code/common/vpp/src -I. -Iinclude -I/home/sirdas/code/common/vpp/src/plugins -Iplugins -I/home/sirdas/code/common/vpp/build-root/install-vpp-native/dpdk/include/dpdk -march=armv8-a+crc -g -O2 -DFORTIFY_SOURCE=2 -fstack-protector -fPIC -Werror -fPIC   -Wno-address-of-packed-member -Wall -MD -MT plugins/dpdk/CMakeFiles/dpdk_plugin.dir/device/init.c.o -MF plugins/dpdk/CMakeFiles/dpdk_plugin.dir/device/init.c.o.d -o plugins/dpdk/CMakeFiles/dpdk_plugin.dir/device/init.c.o   -c /home/sirdas/code/common/vpp/src/plugins/dpdk/device/init.c
In file included from /home/sirdas/code/common/vpp/src/vppinfra/cache.h:41,
                 from /home/sirdas/code/common/vpp/src/vppinfra/dlmalloc.h:525,
                 from /home/sirdas/code/common/vpp/src/vppinfra/mem.h:51,
                 from /home/sirdas/code/common/vpp/src/vppinfra/vec.h:42,
                 from /home/sirdas/code/common/vpp/src/vppinfra/format.h:44,
                 from /home/sirdas/code/common/vpp/src/vppinfra/elf.h:41,
                 from /home/sirdas/code/common/vpp/src/vppinfra/elf_clib.h:41,
                 from /home/sirdas/code/common/vpp/src/vlib/vlib.h:44,
                 from /home/sirdas/code/common/vpp/src/vnet/unix/pcap.h:46,
                 from /home/sirdas/code/common/vpp/src/vnet/vnet.h:45,
                 from /home/sirdas/code/common/vpp/src/plugins/dpdk/device/init.c:15:
/home/sirdas/code/common/vpp/src/plugins/dpdk/device/init.c: In function ‘dpdk_init’:
/home/sirdas/code/common/vpp/src/vppinfra/error_bootstrap.h:85:34: error: static assertion failed: "DPDK RTE CACHE LINE SIZE does not match with 1<<CLIB_LOG2_CACHE_LINE_BYTES"
 #define STATIC_ASSERT(truth,...) _Static_assert(truth, __VA_ARGS__)
                                  ^~~~~~~~~~~~~~
/home/sirdas/code/common/vpp/src/plugins/dpdk/device/init.c:1802:3: note: in expansion of macro ‘STATIC_ASSERT’
   STATIC_ASSERT (RTE_CACHE_LINE_SIZE == 1 << CLIB_LOG2_CACHE_LINE_BYTES,
   ^~~~~~~~~~~~~
/home/sirdas/code/common/vpp/src/plugins/dpdk/device/init.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-address-of-packed-member’ [-Werror]
cc1: all warnings being treated as errors
[762/1155] Building C object vpp/CMakeFiles/vpp.dir/api/api_format.c.o
ninja: build stopped: subcommand failed.
Makefile:691: recipe for target 'vpp-build' failed
make[1]: *** [vpp-build] Error 1
make[1]: Leaving directory '/home/sirdas/code/common/vpp/build-root'
Makefile:353: recipe for target 'build-release' failed
make: *** [build-release] Error 2

Patch-set: 2
Reviewer: Gerrit User 1230 <1230@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>
Label: Verified=0