snort: fix unused result warning for gcc-10
make build-release CC=gcc-10

src/plugins/snort/daq_vpp.c:606:14: error:
ignoring return value of ‘read’ declared with
attribute ‘warn_unused_result’ [-Werror=unused-result]
  606 |       (void) read (qp->enq_fd, &ctr, sizeof (ctr));
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

gcc void cast cannot suppress __attribute((warn_unused_result)),
use __attribute__((unused)) instead.

Type: fix
Fixes: 839b1473e968 ("snort: snort3 plugin and DAQ")
Signed-off-by: Tianyu Li <tianyu.li@arm.com>
Change-Id: I7c7c8c2dbdc47c200b091c23ec2d992266596992