vppapigen: fix json build error
In the makefiles generated by cmake, vppapigen can be executed multiple
times on the same .api file to generate the same JSON file in parallel
if make -j is used. However vppapigen truncates the output JSON file,
possibly leading to a race condition with the following error:

Traceback (most recent call last):
  File "/home/pjhades/code/vpp-upstream/src/vpp-api/vapi/vapi_c_gen.py", line 987, in <module>
    jsonparser = JsonParser(
  File "/home/pjhades/code/vpp-upstream/src/vpp-api/vapi/vapi_json_parser.py", line 365, in __init__
    self.parse_json_file(f)
  File "/home/pjhades/code/vpp-upstream/src/vpp-api/vapi/vapi_json_parser.py", line 377, in parse_json_file
    j = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The error can be reproduced by first creating a cmake build directory
under src/:

mkdir -p src/potato
cd src/potato
cmake ..

and then running the following bash script from the build directory:

set -o errexit
while true; do
    make -j16 clean
    make -j16 api_headers
done

This patch fixes vppapigen by having it first write the JSON output to
a temporary file and then rename it.

Type: fix
Signed-off-by: Jing Peng <jing@meter.com>
Change-Id: Ib6a54f9900e11fbfab700f7b8303fde6eae1abb7