tests: make UnexpectedApiReturnValueError friendlier
- Make the api exception more user and test friendly.
- Introduce new api fn. api_strerror_dump(api_errno=0x7fffffff) for
  list of api errorcode definitions.

Change output from:
  UnexpectedApiReturnValueError: API call failed, expected 0 return value instead of -6 in
  bridge_domain_add_del_reply(_0=148, context=14988, retval=-6)

to:
  UnexpectedApiReturnValueError: sw_interface_add_del_address(address_length=24, is_add=1,
  sw_if_index=3, address='\xac\x10\x01\x02')
  returned 'Address already present on another interface.' (-127).  Expected 0.
  Reply was: sw_interface_add_del_address_reply(_0=89, context=38, retval=-127).
  
An invalid response returns:
  InvalidApiReturnValueError: API function vxlan_gbp_tunnel_add_del(
  tunnel={'src': {'un': {'ip4': IPv4Address(u'172.16.1.1')}, 
  'af': <vl_api_address_family_t.ADDRESS_IP4: 0>}, 'dst': {'un': {
  'ip4': IPv4Address(u'172.16.1.2')}, 'af': <vl_api_address_family_t.ADDRESS_IP4: 0>}, 
  'vni': 1}) returned an invalid return code of (1).
  Please fix the api function to return a value in api_errno.h or at least 
  open a ticket at: https://jira.fd.io/projects/VPP/issues.

Enable tests to access api values/replies.
    with self.assertRaises(UnexpectedApiReturnValueError) as unexpected:
	rv=self.vapi.foo()
	if expected.rv == -60:
	  bar()

    Provides the following to the tests:
        self.ev
        self.rv
        self.reply
        self.api_fn_name
        self.api_fn_args

Type: feature

Change-Id: Ifdabc9db1d0d72c6cd06f666ebc10763c2768747
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>