Update patch set 2
Patch Set 2:

> (1 comment)

Apologies I just saw the date of the merge and I think everything was working fine before that. So this may not be the issue.
I also see pthread_create failure

$ cat /home/sirdas/code/commitb/vpp/build-root/build-vpp-native/vpp/CMakeFiles/CMakeError.log
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/sirdas/code/commitb/vpp/build-root/build-vpp-native/vpp/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_c9741"
[1/2] Building C object CMakeFiles/cmTC_c9741.dir/CheckSymbolExists.c.o
[2/2] Linking C executable cmTC_c9741
FAILED: cmTC_c9741 
: && /usr/lib/ccache/cc -Wno-address-of-packed-member -march=armv8-a+crc -g -O2 -DFORTIFY_SOURCE=2 -fstack-protector -fPIC -Werror   CMakeFiles/cmTC_c9741.dir/CheckSymbolExists.c.o  -o cmTC_c9741   && :
CMakeFiles/cmTC_c9741.dir/CheckSymbolExists.c.o: In function `main':
/home/sirdas/code/commitb/vpp/build-root/build-vpp-native/vpp/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8: undefined reference to `pthread_create'
/home/sirdas/code/commitb/vpp/build-root/build-vpp-native/vpp/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

File /home/sirdas/code/commitb/vpp/build-root/build-vpp-native/vpp/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Performing C SOURCE FILE Test HAVE_GETCPU failed with the following output:

Patch-set: 2