Update patch set 2
Patch Set 2: Code-Review-2 Verified-1

This change breaks compilation with stock / unpatched dpdk 2.2.

/home/damarion/cisco/vpp/build-data/../vnet/vnet/devices/dpdk/vhost_user.c: In function ‘dpdk_vhost_user_set_vring_addr’:
/home/damarion/cisco/vpp/build-data/../vnet/vnet/devices/dpdk/vhost_user.c:568:5: error: ‘struct vhost_virtqueue’ has no member named ‘log_guest_addr’
   vq->log_guest_addr = log;
     ^
/home/damarion/cisco/vpp/build-data/../vnet/vnet/devices/dpdk/vhost_user.c: In function ‘dpdk_vhost_user_get_vring_base’:
/home/damarion/cisco/vpp/build-data/../vnet/vnet/devices/dpdk/vhost_user.c:610:5: error: ‘struct vhost_virtqueue’ has no member named ‘log_guest_addr’
   vq->log_guest_addr = 0;
     ^
/home/damarion/cisco/vpp/build-data/../vnet/vnet/devices/dpdk/vhost_user.c: In function ‘dpdk_vhost_user_socket_read’:
/home/damarion/cisco/vpp/build-data/../vnet/vnet/devices/dpdk/vhost_user.c:1165:23: error: ‘struct virtio_net’ has no member named ‘log_base’
       xd->vu_vhost_dev.log_base += (u64)addr + msg.log.offset;
                       ^
/home/damarion/cisco/vpp/build-data/../vnet/vnet/devices/dpdk/vhost_user.c:1166:23: error: ‘struct virtio_net’ has no member named ‘log_size’
       xd->vu_vhost_dev.log_size = msg.log.size;

Patch-set: 2
Label: Code-Review=-2
Label: Verified=-1