Update patch set 2
Patch Set 2:

PS1 (https://jenkins.fd.io/job/vpp-verify-master-ubuntu1604/12876/console)
shows that the error message would have following form:

Exception: JVpp Registry jar has not been found: /w/workspace/vpp-verify-master-ubuntu1604/build-root/build-vpp-native/vpp/vpp-api/java/jvpp-registry-18.11.jar

Instead of:

Exception: Command ['java', '-cp', '/w/workspace/vpp-verify-master-ubuntu1604/build-root/build-vpp-native/vpp/vpp-api/java/jvpp-registry-18.11.jar:/w/workspace/vpp-verify-master-ubuntu1604/build-root/build-vpp-native/vpp/vpp-api/java/jvpp-acl-18.11.jar', 'io.fd.vpp.jvpp.acl.test.FutureApiTest', '/vpp-unittest-TestJVpp-FgMU_1-vpe-api'] failed with return code: 1.
11:13:51 Process error output: 
11:13:51 Error: Could not find or load main class io.fd.vpp.jvpp.acl.test.FutureApiTest

Patch-set: 2
Reviewer: Gerrit User 174 <174@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>
Label: Code-Review=0