vlib: add exit codes if vpp doesn't start properly
  return non-zero exit codes so the parent process can
  have a hint as to the error.

  In the test framework, this changes:
    framework.VppDiedError: VPP subprocess died unexpectedly
    with return code: 0 [].
  to:
    framework.VppDiedError: VPP subprocess died unexpectedly
    with return code: 5 [VLIB_THREAD_INIT].

Type: feature
Change-Id: Iafc441f9b5a5f1b0499eb13b12579870b783e7f8
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>