crypto: refactor opt_data in vnet_crypto_main_t
opt_data is defined as static array, while in some code, e.g., function
 vnet_crypto_get_op_type, it's used as vec. Refactor opt_data in
vnet_crypto_main_t as vec instead of static array.

src/vnet/crypto/crypto.h:234:70: error: address of array 'cm->opt_data' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
  vnet_crypto_op_data_t *od = ({ do { if ((0 > 0) && ! ((id) < ((cm->opt_data) ? (((vec_header_t *) (cm->opt_data) - 1)->len) : 0)))

Type: fix

Change-Id: I0b6754406e4216ca975bc1da4b5d4ce293a9bb45
Signed-off-by: Lijian Zhang <Lijian.Zhang@arm.com>