Update patch set 1
Patch Set 1: Code-Review+1

I still do not entirely understand what was happening before, but this error:
  Traceback (most recent call last):
    File "/usr/lib/python2.7/multiprocessing/queues.py", line 268, in _feed send(obj)
  IOError: [Errno 32] Broken pipe

is visible ([0], scroll way down) without this, but not ([1] but you need to download, same #) with this.

[0] https://logs.fd.io/production/vex-yul-rot-jenkins-1/csit-vpp-device-master-ubuntu1804-1n-skx/1662/archives/log.html.gz#s1-s1-s1-s1-s1-t2-k1-k2
[1] https://jenkins.fd.io/sandbox/job/vpp-csit-verify-device-master-1n-skx/1/artifact/csit_current/log.html

Patch-set: 1
Reviewer: Gerrit User 1263 <1263@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>
Label: Code-Review=+1