Update patch set 2
Patch Set 2:

> Patch Set 2: Code-Review-1
> 
> it is used and it should only be used during LTO link phase.
> See: src/cmake/library.cmake

Without the proposed changes I am getting the following compile errors:
```
VPP version         : 22.06-rc0~122-ga19ad1c36                                                                                                                                                                                                             VPP library version : 22.06                                                                                                                                                                                                                                GIT toplevel dir    : /home/ruslan/src/vpp                                                                                                                                                                                                                 Build type          : RELEASE                                                                                                                                                                                                                              C compiler          : /home/ruslan/sdk/sysroots/x86_64-pokysdk-linux/usr/bin/x86_64-poky-linux/x86_64-poky-linux-gcc                                                                                                                                       C flags             :  -O2 -pipe -g -feliminate-unused-debug-types                                                                                                                                                                                         Linker flags (apps) : -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now                                                                                                                                                                     Linker flags (libs) : -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now                                                                                                                                                                     Host processor      : x86_64                                                                                                                                                                                                                               Target processor    : corei7-64                                                                                                                                                                                                                            Prefix path         :                                                                                                                                                                                                                                      Install prefix      : /usr/local                                                                                                                                                                                                                           Library dir         : lib/                                                                                                                                                                                                                                 -- Configuring done                                                                                                                                                                                                                                        -- Generating done                                                                                                                                                                                                                                         -- Build files have been written to: /home/ruslan/tmp/vpp                                                                                                                                                                                                  [69/1481] Building C object CMakeFiles/svm/CMakeFiles/svm_objs.dir/svm_fifo.c.o
FAILED: CMakeFiles/svm/CMakeFiles/svm_objs.dir/svm_fifo.c.o
ccache /home/ruslan/sdk/sysroots/x86_64-pokysdk-linux/usr/bin/x86_64-poky-linux/x86_64-poky-linux-gcc   -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/ruslan/sdk/sysroots/corei7-64-poky-linux --sysroot=/home/ruslan/sdk/sysroots/corei7-64-poky-linux -DHAVE_FCNTL64 -D_FORTIFY_SOURCE=2 -I/home/ruslan/src/vpp/src -ICMakeFiles -O2 -pipe -g -feliminate-unused-debug-types  -fPIC -g -Werror -Wall -Wno-address-of-packed-member -O3 -fstack-protector -fno-common -MD -MT CMakeFiles/svm/CMakeFiles/svm_objs.dir/svm_fifo.c.o -MF CMakeFiles/svm/CMakeFiles/svm_objs.dir/svm_fifo.c.o.d -o CMakeFiles/svm/CMakeFiles/svm_objs.dir/svm_fifo.c.o -c /home/ruslan/src/vpp/src/svm/svm_fifo.c
In file included from /home/ruslan/sdk/sysroots/x86_64-pokysdk-linux/usr/lib/x86_64-poky-linux/gcc/x86_64-poky-linux/10.3.0/include/xmmintrin.h:1316,
                 from /home/ruslan/sdk/sysroots/x86_64-pokysdk-linux/usr/lib/x86_64-poky-linux/gcc/x86_64-poky-linux/10.3.0/include/immintrin.h:29,
                 from /home/ruslan/sdk/sysroots/x86_64-pokysdk-linux/usr/lib/x86_64-poky-linux/gcc/x86_64-poky-linux/10.3.0/include/x86intrin.h:32,
                 from /home/ruslan/src/vpp/src/vppinfra/clib.h:48,
                 from /home/ruslan/src/vpp/src/svm/svm_fifo.h:22,
                 from /home/ruslan/src/vpp/src/svm/svm_fifo.c:20:
In function '_mm_storeu_si128',
    inlined from 'u8x16_store_unaligned' at /home/ruslan/src/vpp/src/vppinfra/vector_sse42.h:79:23,
    inlined from 'clib_memcpy_x86_64' at /home/ruslan/src/vpp/src/vppinfra/memcpy_x86_64.h:556:4,
    inlined from 'clib_memcpy_fast' at /home/ruslan/src/vpp/src/vppinfra/string.h:81:3,
    inlined from 'svm_fifo_clone' at /home/ruslan/src/vpp/src/svm/svm_fifo.c:1347:3:
/home/ruslan/sdk/sysroots/x86_64-pokysdk-linux/usr/lib/x86_64-poky-linux/gcc/x86_64-poky-linux/10.3.0/include/emmintrin.h:727:8: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  727 |   *__P = __B;
      |   ~~~~~^~~~~
In file included from /home/ruslan/src/vpp/src/svm/svm_fifo.h:26,
                 from /home/ruslan/src/vpp/src/svm/svm_fifo.c:20:
/home/ruslan/src/vpp/src/svm/svm_fifo.c: In function 'svm_fifo_clone':
/home/ruslan/src/vpp/src/svm/fifo_types.h:45:6: note: at offset 0 to object 'data' with size 0 declared here
   45 |   u8 data[0];                   /**< start of chunk data */
      |      ^~~~
```

Patch-set: 2