vppinfra: fix the errors of compiling and running test_vec.c
Compiling and running test_vec.c fails because
a.) Function clib_mem_usage is obsolete and not defined any more.
b.) Function format_clib_mem_usage is used but not visible in vppinfra
share object.
Fix the error by modifying the outdated wrapper and setting the attribute
of used function visible.

Steps to reproduce the error:
1. Build the release version of VPP by executing 'make build-release' in
vpp root directory.
2. Compile test_vec.c with the gcc compiler in vpp/src/vppinfra
directory using the following command.
gcc -I./../../build-root/install-vpp-native/vpp/include/ -I./../
test_vec.c -L./../../build-root/install-vpp-native/vpp/lib/ -lvppinfra
-o test_vec
3. Compiling errors shows like below.
test_vec.c: In function ‘test_vec_main’:
test_vec.h:230:3: warning: implicit declaration of function ‘clib_mem_usage’; did you mean ‘clib_mem_trace’? [-Wimplicit-function-declaration]
   clib_mem_usage (&_usage);     \
   ^~~~~~~~~~~~~~
test_vec.c:1154:7: note: in expansion of macro ‘memory_snap’
       memory_snap ();
       ^~~~~~~~~~~
/usr/bin/ld: /tmp/cc01B925.o: in function `test_vec_main':
test_vec.c:(.text+0xd1b6): undefined reference to `clib_mem_usage'
/usr/bin/ld: test_vec.c:(.text+0xd1e8): undefined reference to `format_clib_mem_usage'

Type: fix

Change-Id: Ib46b6c03facd69348ea7c1b8b904c1a5de7e1853
Signed-off-by: Jieqiang Wang <jieqiang.wang@arm.com>
Reviewed-by: Lijian Zhang <Lijian.Zhang@arm.com>
Reviewed-by: Tianyu Li <Tianyu.Li@arm.com>