Update patch set 1
Patch Set 1:

Adding Paul as a reviewer. It looks like the patch is essentially reverting some changes from his earlier patch https://gerrit.fd.io/r/c/vpp/+/32000 so let's get his feedback.

Background info for Paul....

Raja reported that when the extended tests are run, some of the VRRP tests always fail with errors like:

==============================================================================
Traceback (most recent call last):
  File "/opt/vpp_dev/vpp/test/test_vrrp.py", line 375, in test_vrrp4_backup_noadv
    pkts = [self.vrrp_adv_packet(prio=prio+10, src_ip=src_ip)]
  File "/opt/vpp_dev/vpp/test/test_vrrp.py", line 200, in vrrp_adv_packet
    dst_ip = self._adv_dest_ip
AttributeError: 'TestVRRP4' object has no attribute '_adv_dest_ip'
==============================================================================

This patch is intended to fix those errors.

Patch-set: 1
Reviewer: Gerrit User 1496 <1496@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>
Reviewer: Gerrit User 366 <366@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>