Update patch set 2
Patch Set 2:

Running the CRCchecker manually... seems found a glitch in crcchecker :-)...

ubuntu@vpp-dev:~/vpp$ git log HEAD~1..
commit 05ebb500105543a7f7207586f5dfa05caef17d68 (HEAD -> master-apicheck)
Author: Paul Vinciguerra <pvinci@vinciconsulting.com>
Date:   Sun May 3 12:30:55 2020 -0400

    vxlan-gpe: update api defaults/fix protocol
    
      - Move defaults from vpp_papi_provider to .api
      - fix 'protocol' typedef
      - rename 'protocol' to 'next_protocol' to avoid future confusion
      - add next_protocol api enum
    
    Type: fix
    
    Change-Id: I22e9bfad49f335becb2649137705130b3b1d0dc0
    Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>
ubuntu@vpp-dev:~/vpp$ extras/scripts/crcchecker.py --check-patchset
vppapigen failed for HEAD~1:src/vnet/vxlan-gpe/vxlan_gpe_types.api with command
 /home/ubuntu/vpp/extras/scripts/../../src/tools/vppapigen/vppapigen.py --git-revision HEAD~1 --includedir src --input src/vnet/vxlan-gpe/vxlan_gpe_types.api CRC
 error: CompletedProcess(args=['/home/ubuntu/vpp/extras/scripts/../../src/tools/vppapigen/vppapigen.py', '--git-revision', 'HEAD~1', '--includedir', 'src', '--input', 'src/vnet/vxlan-gpe/vxlan_gpe_types.api', 'CRC'], returncode=1, stdout=b'', stderr=b"fatal: Path 'src/vnet/vxlan-gpe/vxlan_gpe_types.api' exists on disk, but not in 'HEAD~1'.\nParse error:  src/vnet/vxlan-gpe/vxlan_gpe_types.api: At end of input\n") fatal: Path 'src/vnet/vxlan-gpe/vxlan_gpe_types.api' exists on disk, but not in 'HEAD~1'.
Parse error:  src/vnet/vxlan-gpe/vxlan_gpe_types.api: At end of input

ubuntu@vpp-dev:~/vpp$

Patch-set: 2
CC: Gerrit User 320 <320@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>