Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > The fact that this import error isn't picked up is a bigger problem.  I'm sure it's being swallowed by an except: somewhere.
> 
> Sorry, what's the import error?

Sorry, 

Technically it's a NameError due to the import:
python3
Python 3.9.0a4 (v3.9.0a4:6e02691f30, Feb 25 2020, 18:14:13) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from os import path, remove
>>> path.exists('/tmp/filt.pcap')
False
>>> os.remove('/tmp/dispatch.pcap')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'os' is not defined
>>>

Patch-set: 2