Revert "ioam:trace plugin - trace profile read API"
This reverts commit d24625fbd1775a45ed0f262faf62cb6452aabb45.
oThis is due to veryfy jobs failing with following errors:

21:58:00
/w/workspace/vpp-csit-verify-virl-master/build-data/../plugins/ioam-plugin/ioam/lib-trace/trace_test.c:
In function ‘vl_api_trace_profile_show_config_reply_t_handler’:
21:58:00
/w/workspace/vpp-csit-verify-virl-master/build-data/../plugins/ioam-plugin/ioam/lib-trace/trace_test.c:110:176:
error: ‘TSP_SECONDS’ undeclared (first use in this function)
21:58:00
/w/workspace/vpp-csit-verify-virl-master/build-data/../plugins/ioam-plugin/ioam/lib-trace/trace_test.c:110:176:
note: each undeclared identifier is reported only once for each function
it appears in
21:58:00
/w/workspace/vpp-csit-verify-virl-master/build-data/../plugins/ioam-plugin/ioam/lib-trace/trace_test.c:110:221:
error: ‘TSP_MILLISECONDS’ undeclared (first use in this function)
21:58:00
/w/workspace/vpp-csit-verify-virl-master/build-data/../plugins/ioam-plugin/ioam/lib-trace/trace_test.c:110:277:
error: ‘TSP_MICROSECONDS’ undeclared (first use in this function)

Change-Id: Id2bf0f69638245e861454a42928d3df50025a54a
Signed-off-by: Damjan Marion <damarion@cisco.com>