Subject: [PATCH] dpdk: Newer meson 0.55.3
Fixes error with python 3.12:

ModuleNotFoundError: No module named 'pkg_resources'

'import pkg_resources' removed in 0.55.3

Type: fix

Change-Id: I15c8cf195fd07a0eb2f3b58f895ef4b26cc17b90
Signed-off-by: nucleo <alekcejk@googlemail.com>