tests: fix node variant tests
The skip decorator does not work for variant tests.  The reason is
because the decorator skips looking at a vlib graph node.  The problem
is that the test tries to start vpp with an invalid variant which aborts VPP
before realizing that the test should have been skipped.

  Running each VPPTestCase in a separate background process with 1 parallel process(es)
  21:11:38,289 VPP died shortly after startup, check the output to standard error for possible cause
  21:11:38,296 ------------------------------------------------------------------------------
  21:11:38,297 VPP output to stderr while running TestSKXVariant:
  21:11:38,299 ------------------------------------------------------------------------------
  21:11:38,300
  /vpp/build-root/install-vpp-native/vpp/bin/vpp[2129775]: vlib_early_node_config: please specify a valid node varian

  21:11:38,302 ------------------------------------------------------------------------------

  ==============================================================================
  ERROR: setUpClass (test_node_variants.TestSKXVariant)
  ------------------------------------------------------------------------------
  Traceback (most recent call last):
    File "/ssd/vpp/build-root/build-test/src/test_node_variants.py", line 108, in setUpClass
      super(TestSKXVariant, cls).setUpClass()
    File "/ssd/vpp/build-root/build-test/src/test_node_variants.py", line 41, in setUpClass
      super(TestNodeVariant, cls).setUpClass()
    File "/ssd/src/vpp/test/framework.py", line 590, in setUpClass
      hook.poll_vpp()
    File "/ssd/src/vpp/test/hook.py", line 116, in poll_vpp
      raise framework.VppDiedError(rv=self.test.vpp.returncode)
  framework.VppDiedError: VPP subprocess died unexpectedly with return code: 1 [].

  21:11:38,355 Symlink to failed testcase directory: /tmp/vpp-failed-unittests/vpp-unittest-TestSKXVariant-mswucpg3-FAILED -> vpp-unittest-TestSKXVariant-mswucpg3

Type: test

Change-Id: I2e9511fe1de792eb06649c525ebe4e2a139a1a6b
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>