Update patch set 1
Patch Set 1:

This commit is not blocked by CSIT as there are no tests for netmap in CSIT.

The failure is caused by vpp code - https://logs.fd.io/production/vex-yul-rot-jenkins-1/vpp-csit-verify-device-master-1n-skx/3064/console-timestamp.log.gz:

11:48:03  /w/workspace/vpp-csit-verify-device-master-1n-skx/src/vnet/devices/netmap/netmap_api.c: In function â€vl_api_netmap_create_t_handlerâ€™:
11:48:03  /w/workspace/vpp-csit-verify-device-master-1n-skx/src/vnet/devices/netmap/netmap_api.c:57:30: error: implicit declaration of function â€vl_api_from_api_string_câ€™; did you mean â€vl_api_from_api_stringâ€™? [-Werror=implicit-function-declaration]
11:48:03     if_name = format (0, "%s", vl_api_from_api_string_c (&mp->netmap_if_name));
11:48:03                                ^~~~~~~~~~~~~~~~~~~~~~~~
11:48:03                                vl_api_from_api_string
11:48:03  /w/workspace/vpp-csit-verify-device-master-1n-skx/src/vnet/devices/netmap/netmap_api.c: At top level:
11:48:03  cc1: error: unrecognized command line option â€-Wno-address-of-packed-memberâ€™ [-Werror]
11:48:03  cc1: all warnings being treated as errors

Patch-set: 1
Reviewer: Gerrit User 207 <207@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>
Label: Nomad=0