Tests: Stop swallowing exceptions. Bare exceptions.
* Implement capture specific exceptions and use them.
* Restrict scapy related exceptions to 'Scapy_Exceptions'.
* modified docs to stop suggesting raising Exception:.
* Updated docs to show custom exceptions/exception hierarchy.
* Add strerror type messages to papi.api errors.
    UnexpectedApiReturnValueError: API call failed,
    expected 0 (No error) return value instead of -127
    ("Address already present on another interface")
    in sw_interface_add_del_address_reply

Change-Id: Ib8ed0e502e54e2599867458e0da9c98ab02d5c03
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>