Update patch set 1
Patch Set 1:

I am using an arm64 platform.

I use an external dpdk (following flags set in vpp.mk)
vpp_uses_dpdk_cryptodev_sw = no
vpp_uses_external_dpdk = yes
vpp_dpdk_shared_lib = no


I have many declared-but-never-defined warning/errors due to this missing include such as the following : 

In file included from /root/dpdk/arm64-dpaa-linuxapp-gcc//include/rte_atomic_32.h:44:0,
                 from /root/dpdk/arm64-dpaa-linuxapp-gcc//include/rte_atomic.h:39,
                 from /root/dpdk/arm64-dpaa-linuxapp-gcc//include/rte_ring.h:101,
                 from /root/dpdk/arm64-dpaa-linuxapp-gcc//include/rte_mempool.h:76,
                 from /root/dpdk/arm64-dpaa-linuxapp-gcc//include/rte_mbuf.h:58,
                 from /root/dpdk/arm64-dpaa-linuxapp-gcc//include/rte_crypto.h:48,
                 from /home/gannega/export/vpp/build-data/../src/plugins/dpdk/ipsec/ipsec.h:21,
                 from /home/gannega/export/vpp/build-data/../src/plugins/dpdk/ipsec/esp_encrypt.c:23:
/root/dpdk/arm64-dpaa-linuxapp-gcc//include/generic/rte_atomic.h:386:1: error: 'rte_atomic32_cmpset' used but never defined [-Werror]
 rte_atomic32_cmpset(volatile uint32_t *dst, uint32_t exp, uint32_t src);

Patch-set: 1
Label: Code-Review=0