papi: make UnexpectedApiReturnValueError friendlier
RUNNING EXTENDED TESTS!

Depends-on: https://gerrit.fd.io/r/#/c/20484/

- Make the api exception more user and test friendly.
- Move api exceptions to vpp_api to enable consumption by
  a larger audience than just tests.
- Introduce new api fn. api_strerror_dump(api_errno=0x7fffffff) for
  list of api errorcode definitions.
- Exposes the installed version as:
    self.vapi.vppapiclient.__version__
- Adds __repr__ for Exceptions and serializer types.
- Adds the ability to provide a reversible __repr__: _want_reversible_repr.
- Adds papi tests.
- Adds descriptive message from:
    AttributeError: 'VppApiDynamicMethodHolder' object has no attribute 'no_such_api'
  to:
    VPPApiClientNoSuchApiError: client called: sw_if_interface_dump()
- Increments version semver.

Change output from:
  UnexpectedApiReturnValueError: API call failed, expected 0 return value instead of -127 in sw_inter...val=-127)

to:
  VPPApiClientUnexpectedReturnValueError: sw_interface_add_del_address(address_length=24, is_add=1,
  sw_if_index=3, address='\xac\x10\x01\x02')
  returned 'VNET_API_ERROR_DUPLICATE_IF_ADDRESS: Address already present on another interface.' (-127).  Expected 0.
  Reply was: sw_interface_add_del_address_reply(_0=89, context=38, retval=-127).

An invalid response returns:
  VPPApiClientInvalidReturnValueError: API function vxlan_gbp_tunnel_add_del(
  tunnel={'src': {'un': {'ip4': IPv4Address(u'172.16.1.1')},
  'af': <vl_api_address_family_t.ADDRESS_IP4: 0>}, 'dst': {'un': {
  'ip4': IPv4Address(u'172.16.1.2')}, 'af': <vl_api_address_family_t.ADDRESS_IP4: 0>},
  'vni': 1}) returned an invalid return code of (1).
  Please fix the api function to return a value in api_errno.h or at least
  open a ticket at: https://jira.fd.io/projects/VPP/issues.

Enable tests to access api values/replies.
    with self.assertRaises(VPPApiClientUnexpectedReturnValueError) as unexpected:
	rv=self.vapi.foo()
	if expected.rv == -60:
	  bar()

    Provides the following to the tests:
        self.ev
        self.rv
        self.reply
        self.api_fn_name
        self.api_fn_args

Type: feature

Change-Id: Ifdabc9db1d0d72c6cd06f666ebc10763c2768747
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>