Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review-1
> 
> This breaks under fedora.
> Complete!
> Last metadata expiration check: 0:06:17 ago on Fri 05 Apr 2019 03:54:38 PM UTC.
> No match for argument: python36-ply
> Error: Unable to find a match
> make: *** [Makefile:309: install-dep] Error 1

Ha so this is even worse than what I was thinking - they encode python minor versions in package names and Fedora and CentOS are not even in sync. Sweet.
Anyway your patch seems to be the correct one, so the issue should be fixed soon, hopefully...

Patch-set: 1
Reviewer: Gerrit User 361 <361@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>
Label: Code-Review=0