VPP-1508 python3 tests: xrange
xrange is not supported. Use six.range.

py27 runtests: commands[5] | stestr --test-path ./test run --slowest test_ip4 test_ip6
==============================================================================
IPv4 disabled
==============================================================================
==============================================================================
ICMP Echo Test Case
==============================================================================
{0} test.test_ip4.TestIPDisabled.test_ip_disabled [5.256819s] ... ok
07:24:41,902 Couldn't stat : /tmp/vpp-unittest-TestICMPEcho-hU4IsB/stats.sock
{1} test.test_ip4.TestICMPEcho.test_icmp_echo [0.367035s] ... ok
==============================================================================
IPv4 Deaggregate Routes
==============================================================================
==============================================================================
IPv4 Input Exceptions
==============================================================================
07:24:47,314 Couldn't stat : /tmp/vpp-unittest-TestIPDeag-eE1VgC/stats.sock
{1} test.test_ip4.TestIPDeag.test_ip_deag [5.895646s] ... ok
{0} test.test_ip4.TestIPInput.test_ip_input [5.819001s] ... ok
==============================================================================
IPv4 longest Prefix Match
==============================================================================
==============================================================================
IPv4 Directed Broadcast
==============================================================================
{0} test.test_ip4.TestIPLPM.test_ip_lpm [1.340440s] ... ok
==============================================================================
IPv4 routes via NULL
==============================================================================
07:25:05,879 Couldn't stat : /tmp/vpp-unittest-TestIPDirectedBroadcast-fTMfOy/stats.sock
07:25:07,652 Couldn't stat : /tmp/vpp-unittest-TestIPNull-gxtZ6T/stats.sock
{1} test.test_ip4.TestIPDirectedBroadcast.test_ip_input [3.287311s] ... ok
==============================================================================
IPv4 Load-Balancing
==============================================================================
{0} test.test_ip4.TestIPNull.test_ip_drop [3.025973s] ... ok
==============================================================================
IPv4 Punt Police/Redirect
==============================================================================
{1} test.test_ip4.TestIPLoadBalance.test_ip_load_balance [3.880526s] ... ok
==============================================================================
IPv4 routes via NULL
==============================================================================
07:25:20,023 Couldn't stat : /tmp/vpp-unittest-TestIPPunt-getTLu/stats.sock
{1} test.test_ip4.TestIPNull.test_ip_null [1.660058s] ... ok
{0} test.test_ip4.TestIPPunt.test_ip_punt [8.082276s] ... ok
==============================================================================
IPv4 VLAN-0
==============================================================================
==============================================================================
IPv4 Subnets
==============================================================================
{1} test.test_ip4.TestIPVlan0.test_ip_vlan_0 [0.701733s] ... ok
{0} test.test_ip4.TestIPSubNets.test_ip_sub_nets [3.124540s] ... ok
==============================================================================
IPv4 Test Case
==============================================================================
==============================================================================
FIB - add/update/delete - ip4 routes
==============================================================================
{1} test.test_ip4.TestIPv4.test_fib [5.266539s] ... ok
{0} test.test_ip4.TestIPv4FibCrud.test_1_add_routes [2.560407s] ... ok
{0} test.test_ip4.TestIPv4FibCrud.test_3_add_new_routes [0.157449s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/vpp/test/test_ip4.py", line 509, in test_3_add_new_routes
        self.deleted_routes.remove(x)
    ValueError: list.remove(x): x not in list

==============================================================================
FIB - add/update/delete - ip4 routes
==============================================================================
{0} test.test_ip4.TestIPv4FibCrud.test_4_del_routes [2.430011s] ... ok
==============================================================================
IP4 VRF  Multi-instance Test Case
==============================================================================
{1} test.test_ip4.TestIPv4FibCrud.test_2_del_routes [0.270872s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/vpp/test/test_ip4.py", line 478, in test_2_del_routes
        self.configured_routes.remove(x)
    ValueError: list.remove(x): x not in list

{0} test.test_ip4_vrf_multi_instance.TestIp4VrfMultiInst.test_ip4_vrf_01 [3.817246s] ... ok
{0} test.test_ip4_vrf_multi_instance.TestIp4VrfMultiInst.test_ip4_vrf_03 [0.149311s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/vpp/test/test_ip4_vrf_multi_instance.py", line 465, in test_ip4_vrf_03
        self.create_vrf_and_assign_interfaces(1)
      File "/vpp/test/test_ip4_vrf_multi_instance.py", line 189, in create_vrf_and_assign_interfaces
        pg_if.set_table_ip4(vrf_id)
      File "/vpp/test/vpp_interface.py", line 322, in set_table_ip4
        self.sw_if_index, 0, self.ip4_table_id)
      File "/vpp/test/vpp_papi_provider.py", line 264, in sw_interface_set_table
        'vrf_id': table_id})
      File "/vpp/test/vpp_papi_provider.py", line 196, in api
        raise UnexpectedApiReturnValueError(msg)
    test.vpp_papi_provider.UnexpectedApiReturnValueError: API call failed, expected 0 return value instead of -114 in sw_interface_set_table_reply(_0=91, context=1007, retval=-114)

==============================================================================
IPv4 fragmentation
==============================================================================
{0} test.test_ip4_vrf_multi_instance.TestIp4VrfMultiInst.test_ip4_vrf_04 [1.679339s] ... ok
==============================================================================
ICMPv6 Echo Test Case
==============================================================================
07:26:14,204 Couldn't stat : /tmp/vpp-unittest-TestIPv4Frag-hwQQfK/stats.sock
07:26:15,715 Couldn't stat : /tmp/vpp-unittest-TestICMPv6Echo-5eEEqx/stats.sock
{1} test.test_ip4.TestIPv4Frag.test_frag_large_packets [0.256626s] ... ok
==============================================================================
IRB Test Case
==============================================================================
{0} test.test_ip6.TestICMPv6Echo.test_icmpv6_echo [0.351392s] ... ok
==============================================================================
IPv6 Input Exceptions
==============================================================================
07:26:23,537 Couldn't stat : /tmp/vpp-unittest-TestIpIrb-0R7b2o/stats.sock
07:26:23,915 unexpected time.sleep() result - slept for 0.000288009643555s instead of ~0.000128984451294s!
{0} test.test_ip6.TestIP6Input.test_ip_input [1.853475s] ... ok
{1} test.test_ip4_irb.TestIpIrb.test_ip4_irb_1 [1.062128s] ... ok
==============================================================================
IPv6 Load-Balancing
==============================================================================
{1} test.test_ip4_irb.TestIpIrb.test_ip4_irb_2 [4.619751s] ... ok
==============================================================================
IP4 VRF  Multi-instance Test Case
==============================================================================
{0} test.test_ip6.TestIP6LoadBalance.test_ip6_load_balance [4.571528s] ... ok
{1} test.test_ip4_vrf_multi_instance.TestIp4VrfMultiInst.test_ip4_vrf_02 [0.123005s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/vpp/test/test_ip4_vrf_multi_instance.py", line 445, in test_ip4_vrf_02
        self.reset_vrf_and_remove_from_vrf_list(1)
      File "/vpp/test/test_ip4_vrf_multi_instance.py", line 208, in reset_vrf_and_remove_from_vrf_list
        self.vapi.reset_fib(vrf_id, is_ipv6=0)
      File "/vpp/test/vpp_papi_provider.py", line 1137, in reset_fib
        'is_ipv6': is_ipv6,
      File "/vpp/test/vpp_papi_provider.py", line 196, in api
        raise UnexpectedApiReturnValueError(msg)
    test.vpp_papi_provider.UnexpectedApiReturnValueError: API call failed, expected 0 return value instead of -3 in reset_fib_reply(_0=259, context=1198, retval=-3)

==============================================================================
IPv6 Test Case
==============================================================================
==============================================================================
IPv6 ND ProxyTest Case
==============================================================================
07:26:50,045 Couldn't stat : /tmp/vpp-unittest-TestIPv6-i6yOn7/stats.sock
07:26:50,176 Couldn't stat : /tmp/vpp-unittest-IPv6NDProxyTest-14TEvK/stats.sock
{1} test.test_ip6.IPv6NDProxyTest.test_nd_proxy [5.248187s] ... ok
{0} test.test_ip6.TestIPv6.test_fib [5.846075s] ... ok
==============================================================================
IPv6 Punt Police/Redirect
==============================================================================
{0} test.test_ip6.TestIPv6.test_ns [6.170516s] ... ok
{0} test.test_ip6.TestIPv6.test_ns_duplicates [3.624926s] ... ok
==============================================================================
IPv6 Router Discovery Test Case
==============================================================================
{0} test.test_ip6.TestIPv6RD.test_rd_receive_router_advertisement [0.439121s] ... ok
{1} test.test_ip6.TestIP6Punt.test_ip_punt [6.582046s] ... ok
==============================================================================
IPv6 Deaggregate Routes
==============================================================================
==============================================================================
IPv6 Router Discovery Control Plane Test Case
==============================================================================
{1} test.test_ip6.TestIPDeag.test_ip_deag [6.175234s] ... ok
{0} test.test_ip6.TestIPv6RDControlPlane.test_all [3.072929s] ... ok
==============================================================================
Equal-cost multi-path routing Test Case
==============================================================================
==============================================================================
IPv6 disabled
==============================================================================
07:27:29,441 Couldn't stat : /tmp/vpp-unittest-TestECMP-2aRjyb/stats.sock
{0} test.test_ip_ecmp.TestECMP.test_ip6_ecmp [1.307575s] ... ok
{1} test.test_ip6.TestIPDisabled.test_ip_disabled [5.221591s] ... ok
==============================================================================
IP Multicast Test Case
==============================================================================
==============================================================================
IPv6 routes via NULL
==============================================================================
07:27:43,706 Couldn't stat : /tmp/vpp-unittest-TestIPMcast-MEm7C3/stats.sock
{1} test.test_ip6.TestIPNull.test_ip_null [1.505178s] ... ok
==============================================================================
IPv6 Test Case
==============================================================================
{0} test.test_ip_mcast.TestIPMcast.test_ip6_mcast [8.534775s] ... ok
07:27:54,750 unexpected time.sleep() result - slept for 0.00343084335327s instead of ~0.00111484527588s!
{0} test.test_ip_mcast.TestIPMcast.test_ip6_mcast_vrf [2.425868s] ... ok
==============================================================================
MTU Test Case
==============================================================================
{1} test.test_ip6.TestIPv6.test_rs [5.736628s] ... ok
==============================================================================
IPv6 Router Discovery Test Case
==============================================================================
07:28:05,208 Couldn't stat : /tmp/vpp-unittest-TestMTU-KAMgou/stats.sock
{0} test.test_mtu.TestMTU.test_ip4_mtu [0.949523s] ... ok
{0} test.test_mtu.TestMTU.test_ip6_mtu [1.604654s] ... ok
==============================================================================
P2P Ethernet IPv4 tests
==============================================================================
{1} test.test_ip6.TestIPv6RD.test_rd_send_router_solicitation [2.129658s] ... ok
07:28:14,515 Couldn't stat : /tmp/vpp-unittest-P2PEthernetIPV4-lgktCE/stats.sock
{0} test.test_p2p_ethernet.P2PEthernetIPV4.test_ip4_rx_p2p_subif [0.475985s] ... ok
==============================================================================
P2P Ethernet IPv6 tests
==============================================================================
==============================================================================
IP6 VRF  Multi-instance Test Case
==============================================================================
07:28:20,740 Couldn't stat : /tmp/vpp-unittest-P2PEthernetIPV6-o4bbl9/stats.sock
{0} test.test_p2p_ethernet.P2PEthernetIPV6.test_ip6_rx_p2p_subif [0.485564s] ... ok
{0} test.test_p2p_ethernet.P2PEthernetIPV6.test_ip6_rx_p2p_subif_drop [1.481664s] ... ok
{0} test.test_p2p_ethernet.P2PEthernetIPV6.test_ip6_tx_p2p_subif_drop [1.451261s] ... ok
{1} test.test_ip6_vrf_multi_instance.TestIP6VrfMultiInst.test_ip6_vrf_01 [4.117061s] ... ok
{1} test.test_ip6_vrf_multi_instance.TestIP6VrfMultiInst.test_ip6_vrf_02 [2.378875s] ... ok
{1} test.test_ip6_vrf_multi_instance.TestIP6VrfMultiInst.test_ip6_vrf_03 [3.559109s] ... ok
{1} test.test_ip6_vrf_multi_instance.TestIP6VrfMultiInst.test_ip6_vrf_04 [1.767533s] ... ok
==============================================================================
P2P Ethernet IPv4 tests
==============================================================================
{1} test.test_p2p_ethernet.P2PEthernetIPV4.test_ip4_rx_p2p_subif_route [0.464074s] ... ok
{1} test.test_p2p_ethernet.P2PEthernetIPV4.test_ip4_tx_p2p_subif [0.545976s] ... ok
{1} test.test_p2p_ethernet.P2PEthernetIPV4.test_ip4_tx_p2p_subif_drop [1.436494s] ... ok
==============================================================================
P2P Ethernet IPv6 tests
==============================================================================
07:28:49,345 Couldn't stat : /tmp/vpp-unittest-P2PEthernetIPV6-cnID8T/stats.sock
{1} test.test_p2p_ethernet.P2PEthernetIPV6.test_ip6_rx_p2p_subif_route [0.502587s] ... ok
{1} test.test_p2p_ethernet.P2PEthernetIPV6.test_ip6_tx_p2p_subif [0.541415s] ... ok

==============================
Failed 4 tests - output below:
==============================

test.test_ip4.TestIPv4FibCrud.test_3_add_new_routes
---------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/vpp/test/test_ip4.py", line 509, in test_3_add_new_routes
        self.deleted_routes.remove(x)
    ValueError: list.remove(x): x not in list

test.test_ip4.TestIPv4FibCrud.test_2_del_routes
-----------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/vpp/test/test_ip4.py", line 478, in test_2_del_routes
        self.configured_routes.remove(x)
    ValueError: list.remove(x): x not in list

test.test_ip4_vrf_multi_instance.TestIp4VrfMultiInst.test_ip4_vrf_03
--------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/vpp/test/test_ip4_vrf_multi_instance.py", line 465, in test_ip4_vrf_03
        self.create_vrf_and_assign_interfaces(1)
      File "/vpp/test/test_ip4_vrf_multi_instance.py", line 189, in create_vrf_and_assign_interfaces
        pg_if.set_table_ip4(vrf_id)
      File "/vpp/test/vpp_interface.py", line 322, in set_table_ip4
        self.sw_if_index, 0, self.ip4_table_id)
      File "/vpp/test/vpp_papi_provider.py", line 264, in sw_interface_set_table
        'vrf_id': table_id})
      File "/vpp/test/vpp_papi_provider.py", line 196, in api
        raise UnexpectedApiReturnValueError(msg)
    test.vpp_papi_provider.UnexpectedApiReturnValueError: API call failed, expected 0 return value instead of -114 in sw_interface_set_table_reply(_0=91, context=1007, retval=-114)

test.test_ip4_vrf_multi_instance.TestIp4VrfMultiInst.test_ip4_vrf_02
--------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/vpp/test/test_ip4_vrf_multi_instance.py", line 445, in test_ip4_vrf_02
        self.reset_vrf_and_remove_from_vrf_list(1)
      File "/vpp/test/test_ip4_vrf_multi_instance.py", line 208, in reset_vrf_and_remove_from_vrf_list
        self.vapi.reset_fib(vrf_id, is_ipv6=0)
      File "/vpp/test/vpp_papi_provider.py", line 1137, in reset_fib
        'is_ipv6': is_ipv6,
      File "/vpp/test/vpp_papi_provider.py", line 196, in api
        raise UnexpectedApiReturnValueError(msg)
    test.vpp_papi_provider.UnexpectedApiReturnValueError: API call failed, expected 0 return value instead of -3 in reset_fib_reply(_0=259, context=1198, retval=-3)

======
Totals
======
Ran: 57 tests in 266.0000 sec.
 - Passed: 53
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 4
Sum of execute time for each test: 157.3925 sec.

==============
Worker Balance
==============
 - Worker 0 (29 tests) => 0:03:52.608995
 - Worker 1 (28 tests) => 0:04:08.615473
Test id                                        Runtime (s)
---------------------------------------------  -----------
test.test_ip_mcast.TestIPMcast.test_ip6_mcast  8.535
test.test_ip4.TestIPPunt.test_ip_punt          8.082
test.test_ip6.TestIP6Punt.test_ip_punt         6.582
test.test_ip6.TestIPDeag.test_ip_deag          6.175
test.test_ip6.TestIPv6.test_ns                 6.171
test.test_ip4.TestIPDeag.test_ip_deag          5.896
test.test_ip6.TestIPv6.test_fib                5.846
test.test_ip4.TestIPInput.test_ip_input        5.819
test.test_ip6.TestIPv6.test_rs                 5.737
test.test_ip4.TestIPv4.test_fib                5.267
ERROR: InvocationError for command '/vpp/.tox/py27/bin/stestr --test-path ./test run --slowest test_ip4 test_ip6' (exited with code 1)
______________________________________________________ summary ______________________________________________________
ERROR:   py27: commands failed
Change-Id: Id9f6ecb4897386f790d82ab908963e4971a3aac8
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>